name: CI FullStackPractice API

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

permissions:
  contents: read

jobs:
  backend:
    name: Validar backend
    runs-on: ubuntu-latest

    steps:
      - name: Obter código-fonte
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar dependências
        run: >
          dotnet restore
          backend/FullStackPractice.Api.csproj

      - name: Compilar backend
        run: >
          dotnet build
          backend/FullStackPractice.Api.csproj
          --configuration Release
          --no-restore
